dist: xenial  

language: python

python:
  - "3.7"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run my_sanic_app_my_sanic_app_1 sh -c "pytest && flake8"