dist: xenial  

language: python

python:
  - "3.7"

services:
  - docker

before_script: 
  - pip install docker-compose
  - pip install -r requirements.txt

script:
  - docker-compose run my_sanic_app sh -c "pytest && flake8"