language: python

python:
  - "3.6"

services:
  - docker

before_script:
  - pip install docker-compose

script: 
  - docker-compose run my_sanic_app sh -c "pytest && black ."
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t $DOCKER_USERNAME/my_sanic_app:latest .
  - docker push $DOCKER_USERNAME/my_sanic_app:latest
  